export const DEFAULT_WEATHER = {
  "location": {
    "name": "London",
    "region": "London",
    "country": "United Kingdom",
    "lat": 0,
    "lon": 0,
    "tz_id": "London",
    "localtime_epoch": 1721981457,
    "localtime": "2024-07-26 1:10"
  },
  "current": {
    "last_updated_epoch": 1721980800,
    "last_updated": "2024-07-26 01:00",
    "temp": 0,
    "is_day": 0,
    "condition": {
      "text": "Clear",
      "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
      "code": 1000
    },
    "wind": 0,
    "wind_degree": 0,
    "wind_dir": "NW",
    "pressure": 0,
    "precip": 0.0,
    "humidity": 0,
    "cloud": 0,
    "feelslike": 0,
    "windchill": 0,
    "headindex": 0,
    "dewpoint": 0,
    "vis": 0,
    "uv": 0,
    "gust": 0,
  },
  "forecast": {
    "forecastday": [
      {
	"date": "2024-07-26",
                "date_epoch": 1721952000,
                "day": {
                    "maxtemp": 0,
                    "mintemp": 0,
                    "avgtemp": 0,
                    "maxwind": 0,
                    "totalprecip": 0,
                    "totalsnow": 0,
                    "avgvis": 0,
                    "avghumidity": 0,
                    "daily_will_it_rain": 0,
                    "daily_chance_of_rain": 0,
                    "daily_will_it_snow": 0,
                    "daily_chance_of_snow": 0,
                    "condition": {
                        "text": "Sunny",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                        "code": 1000
                    },
                    "uv": 0,
                },
                "astro": {
                    "sunrise": "06:01 AM",
                    "sunset": "08:10 PM",
                    "moonrise": "11:32 PM",
                    "moonset": "12:01 PM",
                    "moon_phase": "Waning Gibbous",
                    "moon_illumination": 0,
                    "is_moon_up": 0,
                    "is_sun_up": 0,
                },
                "hour": [
                    {
                        "time_epoch": 1721977200,
                        "time": "2024-07-26 00:00",
                        "temp": 0,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind": 0,
                        "wind_degree": 0,
                        "wind_dir": "N",
                        "pressure": 0,
                        "precip": 0,
                        "snow": 0,
                        "humidity": 0,
                        "cloud": 0,
                        "feelslike": 0,
                        "windchill": 0,
                        "heatindex": 0,
                        "dewpoint": 0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis": 0,
                        "gust": 0,
                        "uv": 0
                    },
                    {
                        "time_epoch": 1721980800,
                        "time": "2024-07-26 01:00",
                        "temp": 0,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind": 0,
                        "wind_degree": 0,
                        "wind_dir": "N",
                        "pressure": 0,
                        "precip": 0,
                        "snow": 0,
                        "humidity": 0,
                        "cloud": 0,
                        "feelslike": 0,
                        "windchill": 0,
                        "heatindex": 0,
                        "dewpoint": 0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis": 0,
                        "gust": 0,
                        "uv": 0
                    },
                    {
                        "time_epoch": 1721984400,
                        "time": "2024-07-26 02:00",
                        "temp": 0,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind": 0,
                        "wind_degree": 0,
                        "wind_dir": "N",
                        "pressure": 0,
                        "precip": 0,
                        "snow": 0,
                        "humidity": 0,
                        "cloud": 0,
                        "feelslike": 0,
                        "windchill": 0,
                        "heatindex": 0,
                        "dewpoint": 0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis": 0,
                        "gust": 0,
                        "uv": 0
                    },
                    {
                        "time_epoch": 1721988000,
                        "time": "2024-07-26 03:00",
                        "temp": 0,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind": 0,
                        "wind_degree": 0,
                        "wind_dir": "N",
                        "pressure": 0,
                        "precip": 0,
                        "snow": 0,
                        "humidity": 0,
                        "cloud": 0,
                        "feelslike": 0,
                        "windchill": 0,
                        "heatindex": 0,
                        "dewpoint": 0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis": 0,
                        "gust": 0,
                        "uv": 0
                    },
                    {
                        "time_epoch": 1721991600,
                        "time": "2024-07-26 04:00",
                        "temp": 0,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind": 0,
                        "wind_degree": 0,
                        "wind_dir": "N",
                        "pressure": 0,
                        "precip": 0,
                        "snow": 0,
                        "humidity": 0,
                        "cloud": 0,
                        "feelslike": 0,
                        "windchill": 0,
                        "heatindex": 0,
                        "dewpoint": 0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis": 0,
                        "gust": 0,
                        "uv": 0
                    },
                    {
                        "time_epoch": 1721995200,
                        "time": "2024-07-26 05:00",
                        "temp": 0,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind": 0,
                        "wind_degree": 0,
                        "wind_dir": "N",
                        "pressure": 0,
                        "precip": 0,
                        "snow": 0,
                        "humidity": 0,
                        "cloud": 0,
                        "feelslike": 0,
                        "windchill": 0,
                        "heatindex": 0,
                        "dewpoint": 0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis": 0,
                        "gust": 0,
                        "uv": 0
                    },
                    {
                        "time_epoch": 1721998800,
                        "time": "2024-07-26 06:00",
                        "temp": 0,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind": 0,
                        "wind_degree": 0,
                        "wind_dir": "N",
                        "pressure": 0,
                        "precip": 0,
                        "snow": 0,
                        "humidity": 0,
                        "cloud": 0,
                        "feelslike": 0,
                        "windchill": 0,
                        "heatindex": 0,
                        "dewpoint": 0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis": 0,
                        "gust": 0,
                        "uv": 0
                    },
                    {
                        "time_epoch": 1722002400,
                        "time": "2024-07-26 07:00",
                        "temp": 0,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind": 0,
                        "wind_degree": 0,
                        "wind_dir": "N",
                        "pressure": 0,
                        "precip": 0,
                        "snow": 0,
                        "humidity": 0,
                        "cloud": 0,
                        "feelslike": 0,
                        "windchill": 0,
                        "heatindex": 0,
                        "dewpoint": 0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis": 0,
                        "gust": 0,
                        "uv": 7.0
                    },
                    {
                        "time_epoch": 1722006000,
                        "time": "2024-07-26 08:00",
                        "temp": 0,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind": 0,
                        "wind_degree": 0,
                        "wind_dir": "N",
                        "pressure": 0,
                        "precip": 0,
                        "snow": 0,
                        "humidity": 0,
                        "cloud": 0,
                        "feelslike": 0,
                        "windchill": 0,
                        "heatindex": 0,
                        "dewpoint": 0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis": 0,
                        "gust": 0,
                        "uv": 7.0
                    },
                    {
                        "time_epoch": 1722009600,
                        "time": "2024-07-26 09:00",
                        "temp": 0,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind": 0,
                        "wind_degree": 0,
                        "wind_dir": "N",
                        "pressure": 0,
                        "precip": 0,
                        "snow": 0,
                        "humidity": 0,
                        "cloud": 0,
                        "feelslike": 0,
                        "windchill": 0,
                        "heatindex": 0,
                        "dewpoint": 0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis": 0,
                        "gust": 0,
                        "uv": 8.0
                    },
                    {
                        "time_epoch": 1722013200,
                        "time": "2024-07-26 10:00",
                        "temp": 0,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind": 0,
                        "wind_degree": 0,
                        "wind_dir": "N",
                        "pressure": 0,
                        "precip": 0,
                        "snow": 0,
                        "humidity": 0,
                        "cloud": 0,
                        "feelslike": 0,
                        "windchill": 0,
                        "heatindex": 0,
                        "dewpoint": 0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis": 0,
                        "gust": 0,
                        "uv": 8.0
                    },
                    {
                        "time_epoch": 1722016800,
                        "time": "2024-07-26 11:00",
                        "temp": 0,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind": 0,
                        "wind_degree": 0,
                        "wind_dir": "N",
                        "pressure": 0,
                        "precip": 0,
                        "snow": 0,
                        "humidity": 0,
                        "cloud": 0,
                        "feelslike": 0,
                        "windchill": 0,
                        "heatindex": 0,
                        "dewpoint": 0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis": 0,
                        "gust": 0,
                        "uv": 9.0
                    },
                    {
                        "time_epoch": 1722020400,
                        "time": "2024-07-26 12:00",
                        "temp": 0,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind": 0,
                        "wind_degree": 0,
                        "wind_dir": "N",
                        "pressure": 0,
                        "precip": 0,
                        "snow": 0,
                        "humidity": 0,
                        "cloud": 0,
                        "feelslike": 0,
                        "windchill": 0,
                        "heatindex": 0,
                        "dewpoint": 0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis": 0,
                        "gust": 0,
                        "uv": 9.0
                    },
                    {
                        "time_epoch": 1722024000,
                        "time": "2024-07-26 13:00",
                        "temp": 0,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind": 0,
                        "wind_degree": 0,
                        "wind_dir": "N",
                        "pressure": 0,
                        "precip": 0,
                        "snow": 0,
                        "humidity": 0,
                        "cloud": 0,
                        "feelslike": 0,
                        "windchill": 0,
                        "heatindex": 0,
                        "dewpoint": 0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis": 0,
                        "gust": 0,
                        "uv": 9.0
                    },
                    {
                        "time_epoch": 1722027600,
                        "time": "2024-07-26 14:00",
                        "temp": 0,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind": 0,
                        "wind_degree": 0,
                        "wind_dir": "N",
                        "pressure": 0,
                        "precip": 0,
                        "snow": 0,
                        "humidity": 0,
                        "cloud": 0,
                        "feelslike": 0,
                        "windchill": 0,
                        "heatindex": 0,
                        "dewpoint": 0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis": 0,
                        "gust": 0,
                        "uv": 10.0
                    },
                    {
                        "time_epoch": 1722031200,
                        "time": "2024-07-26 15:00",
                        "temp": 0,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind": 0,
                        "wind_degree": 0,
                        "wind_dir": "N",
                        "pressure": 0,
                        "precip": 0,
                        "snow": 0,
                        "humidity": 0,
                        "cloud": 0,
                        "feelslike": 0,
                        "windchill": 0,
                        "heatindex": 0,
                        "dewpoint": 0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis": 0,
                        "gust": 0,
                        "uv": 10.0
                    },
                    {
                        "time_epoch": 1722034800,
                        "time": "2024-07-26 16:00",
                        "temp": 0,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind": 0,
                        "wind_degree": 0,
                        "wind_dir": "N",
                        "pressure": 0,
                        "precip": 0,
                        "snow": 0,
                        "humidity": 0,
                        "cloud": 0,
                        "feelslike": 0,
                        "windchill": 0,
                        "heatindex": 0,
                        "dewpoint": 0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis": 0,
                        "gust": 0,
                        "uv": 10.0
                    },
                    {
                        "time_epoch": 1722038400,
                        "time": "2024-07-26 17:00",
                        "temp": 0,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind": 0,
                        "wind_degree": 0,
                        "wind_dir": "N",
                        "pressure": 0,
                        "precip": 0,
                        "snow": 0,
                        "humidity": 0,
                        "cloud": 0,
                        "feelslike": 0,
                        "windchill": 0,
                        "heatindex": 0,
                        "dewpoint": 0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis": 0,
                        "gust": 0,
                        "uv": 10.0
                    },
                    {
                        "time_epoch": 1722042000,
                        "time": "2024-07-26 18:00",
                        "temp": 0,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind": 0,
                        "wind_degree": 0,
                        "wind_dir": "N",
                        "pressure": 0,
                        "precip": 0,
                        "snow": 0,
                        "humidity": 0,
                        "cloud": 0,
                        "feelslike": 0,
                        "windchill": 0,
                        "heatindex": 0,
                        "dewpoint": 0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis": 0,
                        "gust": 0,
                        "uv": 9.0
                    },
                    {
                        "time_epoch": 1722045600,
                        "time": "2024-07-26 19:00",
                        "temp": 0,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind": 0,
                        "wind_degree": 0,
                        "wind_dir": "N",
                        "pressure": 0,
                        "precip": 0,
                        "snow": 0,
                        "humidity": 0,
                        "cloud": 0,
                        "feelslike": 0,
                        "windchill": 0,
                        "heatindex": 0,
                        "dewpoint": 0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis": 0,
                        "gust": 0,
                        "uv": 9.0
                    },
                    {
                        "time_epoch": 1722049200,
                        "time": "2024-07-26 20:00",
                        "temp": 0,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind": 0,
                        "wind_degree": 0,
                        "wind_dir": "N",
                        "pressure": 0,
                        "precip": 0,
                        "snow": 0,
                        "humidity": 0,
                        "cloud": 0,
                        "feelslike": 0,
                        "windchill": 0,
                        "heatindex": 0,
                        "dewpoint": 0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis": 0,
                        "gust": 0,
                        "uv": 8.0
                    },
                    {
                        "time_epoch": 1722052800,
                        "time": "2024-07-26 21:00",
                        "temp": 0,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind": 0,
                        "wind_degree": 0,
                        "wind_dir": "N",
                        "pressure": 0,
                        "precip": 0,
                        "snow": 0,
                        "humidity": 0,
                        "cloud": 0,
                        "feelslike": 0,
                        "windchill": 0,
                        "heatindex": 0,
                        "dewpoint": 0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis": 0,
                        "gust": 0,
                        "uv": 0
                    },
                    {
                        "time_epoch": 1722056400,
                        "time": "2024-07-26 22:00",
                        "temp": 0,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind": 0,
                        "wind_degree": 0,
                        "wind_dir": "N",
                        "pressure": 0,
                        "precip": 0,
                        "snow": 0,
                        "humidity": 0,
                        "cloud": 0,
                        "feelslike": 0,
                        "windchill": 0,
                        "heatindex": 0,
                        "dewpoint": 0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis": 0,
                        "gust": 0,
                        "uv": 0
                    },
                    {
                        "time_epoch": 1722060000,
                        "time": "2024-07-26 23:00",
                        "temp": 0,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind": 0,
                        "wind_degree": 0,
                        "wind_dir": "N",
                        "pressure": 0,
                        "precip": 0,
                        "snow": 0,
                        "humidity": 0,
                        "cloud": 0,
                        "feelslike": 0,
                        "windchill": 0,
                        "heatindex": 0,
                        "dewpoint": 0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis": 0,
                        "gust": 0,
                        "uv": 0
                    }
                ]
            }
        ]
    }
}
